### ISSUE TITLE
ClubTests 테스트코드 수정 필요

### ISSUE THREAD

**Issue by junsyun22** [yourfootmyfoot/Footlog-BackEnd#58]
## 🐛 어떤 버그인가요?
- 버그 이름: 존재하지 않는 파일 (UserRole, User)
- 버그 발생 위치: footlog-backend/src/test/java/com/yfmf/footlog/domain/club/ClubTests.java:8

- 버그 상세 설명: 

```
/Users/junsyun/workspace/footlog-backend/src/test/java/com/yfmf/footlog/domain/club/ClubTests.java:8: error: cannot find symbol
import com.yfmf.footlog.users.UserRole;
                             ^
  symbol:   class UserRole
  location: package com.yfmf.footlog.users
```

## 🔍 어떤 상황에서 겪으셨나요?
- 상황 설명: 테스트코드 실행

## 📝 ETC
- 기타 사항: 기타 필요한 사항이나 추가로 제공할 정보가 있다면 적어 주세요.

**Comment by HyupTree** [comment]
10월 4일 내로 코드 수정예정
