### ISSUE TITLE
[Discussion] AOP 어떻게 적용할것인가?

### ISSUE THREAD

**Issue by HyupTree** [yourfootmyfoot/Footlog-BackEnd#60]
# 1. 직접 로그를 남기는 방식의 장단점

### 장점:
- **명확성**: 어떤 코드에서 로그가 남겨지는지 코드만 봐도 명확하게 알 수 있음.
- **컨트롤 용이성**: 메소드마다 다른 로그 포맷이나 조건을 적용할 수 있음.

### 단점:
- **중복 코드**: 여러 메소드에서 동일한 로그 메시지를 남겨야 할 경우, 코드가 중복됨.
- **유지 보수 어려움**: 나중에 로그 메시지 형식이나 로그를 남기는 방식을 변경해야 하면, 모든 메소드를 일일이 수정해야 함.
- **핵심 로직과 혼합**: 비즈니스 로직과 로그 코드가 뒤섞이게 되어 코드가 지저분해지고 가독성이 떨어질 수 있음.

# 2. AOP를 이용한 로그 남기기 방식의 장단점

### 장점:
- **중복 제거**: 여러 메소드에서 공통적으로 적용할 로깅 로직을 하나의 Aspect로 관리할 수 있어서, 중복 코드를 제거할 수 있음.
- **유지 보수 용이성**: 로깅 방식이나 로그 메시지를 수정해야 할 경우, AOP Aspect 하나만 수정하면 모든 메소드에 적용됨.
- **코드 분리**: 핵심 비즈니스 로직과 로그 로직을 분리할 수 있어서, 비즈니스 로직을 더 깔끔하게 유지할 수 있음.

### 단점:
- **직접적이지 않음**: AOP를 처음 접하는 개발자들은 "이 로그가 어디서 발생하는가"를 코드만 보고 바로 이해하기 어려울 수 있음.
- **복잡성 증가**: AOP가 너무 많이 사용되면 코드 흐름을 파악하기 어려워질 수 있고, 디버깅이 까다로워질 수 있음.

# 3. 상황에 따른 선택 기준

- **전체적인 로그 정책**을 적용하거나 **공통 기능**(로그, 트랜잭션, 보안 검사 등)을 여러 메소드에 걸쳐 적용해야 할 때는 AOP가 적합함. AOP를 이용하면 비즈니스 로직과 공통된 기능을 깔끔하게 분리할 수 있기 때문.

- 반면, **특정 메소드에서만** 다른 로그를 남기거나, **메소드의 동작 방식에 따라 다른 로그 메시지를 남겨야** 하는 경우에는 직접 로그를 남기는 방식이 더 명확하고 컨트롤하기 쉬움.

**Comment by JungHyeonmin** [comment]
찾아봐부셔서 감사합니다. 코드 안에서 사용허는 로그들을 확인해보고 코멘트 남기겠습니다!
